### ISSUE TITLE
 Unhandled Exception: MissingPluginException(requestPermissions)

### ISSUE THREAD

**Issue by RubenGarcia** [juliansteenbakker/flutter_ble_peripheral#151]
```
FlutterBlePeripheral flutterBlePeripheral = FlutterBlePeripheral();
BluetoothPeripheralState peripheralPermission = await flutterBlePeripheral.requestPermission();
```
throws this, although the permission is granted. Please investigate.
```
E/flutter ( 2983): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel dev.steenbakker.flutter_ble_peripheral/ble_state)
E/flutter ( 2983): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter ( 2983): <asynchronous suspension>
E/flutter ( 2983): #1      FlutterBlePeripheral.requestPermission (package:flutter_ble_peripheral/src/flutter_ble_peripheral.dart:135:9)
E/flutter ( 2983): <asynchronous suspension>
```

Android 12 (Pixel 3).
```
  flutter_ble_peripheral:
    dependency: "direct main"
    description:
      name: flutter_ble_peripheral
      sha256: aab19e5268f90237ab02cd084844596c37f76285f93759709742bab5627a76ac
      url: "https://pub.dev"
    source: hosted
    version: "1.2.1"
```
I followed the instructions on
https://pub.dev/packages/flutter_ble_peripheral/install
but cloning your repository, the example app works.
Please add any additional configuration to 
https://pub.dev/packages/flutter_ble_peripheral/install
